# Generated by Django 3.1.7 on 2021-05-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderissue',
            name='issue_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
