# Generated by Django 3.1.7 on 2021-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210414_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='brewer',
            field=models.CharField(default='n/a', max_length=254),
        ),
    ]
