# Generated by Django 3.1.7 on 2021-04-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210422_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brewer',
            field=models.CharField(default='', max_length=254),
        ),
    ]
