# Generated by Django 3.1.7 on 2021-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210422_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brewer',
            field=models.CharField(max_length=254),
        ),
    ]
