# Generated by Django 3.1.7 on 2021-05-07 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210506_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MaxValueValidator(50, message=None), django.core.validators.MinValueValidator(0, message=None)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(100, message=None), django.core.validators.MinValueValidator(1, message=None)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000, message=None), django.core.validators.MinValueValidator(100, message=None)]),
        ),
    ]
